[server]
bind_addr = "0.0.0.0:4003"
default_token = "change_this_token"

[server.services.SW1]
type = "tcp"
local_addr = "127.0.0.1:10003"

[server.services.SW2]
type = "tcp"
local_addr = "127.0.0.1:20003"